target-version = "py311"
line-length = 120

[lint]
select = ["E", "F", "I", "UP", "B"]
ignore = ["E501", "B008", "E402", "F401", "I001", "UP007", "UP035"]

[lint.per-file-ignores]
"backend/migrations/**" = ["E501"]
