[pytest]
testpaths = app/tests
addopts =
    --cov=app
    --cov-report=term-missing
    --cov-report=html:coverage_html
    --cov-report=xml:coverage.xml
    --cov-fail-under=70
filterwarnings =
    ignore::DeprecationWarning:passlib
